teste: Plugin Funcionando, Voce Recebeu Dois diamantes.
trabalho: No RLife, tem a possibilidade de trabalhar. Escolha seu emprego /minerador, /tijoleiro. Saiba que cada escolha resultará em um tempo para que seja feita a troca de emprego.